config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    resources :decks
  end

  resources :sessions, only: [ :new, :create, :destroy ]
  
  resources :decks do
    resources :cards
    resources :rounds
  end

  resources :cards

  resources :rounds, only: [ :new, :show, :create, :index ] do
    resources :guesses
  end

  root 'welcome#index'

  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'
  delete 'delete_deck' => 'decks#destroy'

end

app/models/card.rb
class Card < ActiveRecord::Base
	
	has_attached_file        :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	belongs_to               :deck
	has_many                 :guesses
	has_many                 :rounds, :through => :guesses

  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  	
  	def number_right
  		if self.guesses
  			self.guesses.where(answer: "YES").count
  		end
  	end

  	def number_wrong
  		if self.guesses
  			self.guesses.where(answer: "NO").count
  		end
  	end

end

app/models/deck.rb
class Deck < ActiveRecord::Base

	belongs_to  :user
	has_many    :cards, dependent: :destroy
	has_many    :rounds, dependent: :destroy

	validates   :name, presence: true

end

app/models/guess.rb
class Guess < ActiveRecord::Base

	has_one    :user, :through => :round
	belongs_to :round
	belongs_to :card

	validates  :answer, presence: true

	def right?
		self.answer == "YES"
	end

	def wrong?
		self.answer == "NO"
	end


end

app/models/round.rb
class Round < ActiveRecord::Base
	
	has_many    :guesses, dependent: :destroy
	has_many    :cards, :through => :guesses
	belongs_to  :user
	belongs_to  :deck

	def current_card
		guessed_cards  = self.guesses.pluck(:card_id)
		missing_cards = self.deck.cards.reject { |u| guessed_cards.include?(u.id) }
		return missing_cards.first
	end

	def complete?
		self.deck.cards.size == self.guesses.size
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	
	  has_secure_password
	  has_many :decks
	  has_many :rounds
	  has_many :cards, through: :decks
	  has_many :guesses, through: :rounds

	  validates :username, presence: true, length: {in: 8..20}
	  validates :email, presence: true

	  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find session[:user_id] if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def new
		@card = Card.new
		@deck = Deck.find(params[:deck_id])
	end

	def create
		@card = Card.new(card_params)
		if @card.save
			redirect_to deck_path(id: @card.deck_id)
		else
			@errors = @user.errors.full_messages
			render new_deck_path
		end
	end

	def destroy
		Card.find(params[:id]).destroy
    	redirect_to user_path(current_user)
	end

	private

	def card_params
		card_params = params.require(:card).permit(:name, :title, :description,:deck_id,:avatar)
	end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

	def new
		@deck = Deck.new
	end

	def create
		@deck = Deck.new(deck_params)
		if @deck.save
			redirect_to deck_path(id: @deck.id)
		else
			@errors = @user.errors.full_messages
			render new_deck_card_path
		end
	end

	def show
		@deck = Deck.includes(:cards).find_by(id: params[:id])
	end

	def destroy
		Deck.find(params[:id]).destroy
    	redirect_to user_path(current_user)
	end

	private

	def deck_params
		deck_params = params.require(:deck).permit(:name).merge(user:current_user)
	end

end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

	def new
		@guess = Guess.new
	end

	def create
		@guess = Guess.create(guess_params)
		if @guess.save
			redirect_to round_path(@guess.round)
		end
	end
	
	private

	def guess_params
		guess_params = params.permit(:round_id, :card_id, :answer)
	end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController

	def create
		@round = Round.new(deck_id: params[:deck_id],user:current_user)
		if @round.save
			redirect_to round_path(@round)
		end
	end

	def show
		@round = Round.includes(:guesses, deck: [:cards]).find(params[:id])
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
      @user = User.find_by(email: params[:email])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to user_path(id: current_user.id)
      else
        flash[:notice] = "Invalid email or password"
        redirect_to new_session_path
      end
    end

    def destroy
      session.clear
      redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.all
	end

	def new
		@user = User.new
	end

	def show
		@user = User.includes(:decks,decks: [:cards]).find_by(id: params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to user_path(id: @user.id)
		else
			@errors = @user.errors.full_messages
			render new_user_path
		end
	end

	private

	def user_params
		user_params = params.require(:user).permit(:username,:email,:password)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/new.html.erb
<div class="form-container">

  <h2 class="sub-title"> CREATE A NEW CARD </h2>

  <% if @errors %>
  <% @errors.each do |error| %>
  <p class="error"><%= error %></p>
  <% end %>
  <% end %>

  <%= form_for @card, url: cards_path, html: { multipart: true } do |f| %>
  <fieldset id="form">
    <div class="input-options">
      <%= f.label :photo %>
      <%= f.file_field :avatar %>
    </div>
    <div class="input-options">
      <%= f.label :name %>
      <%= f.text_field :name, :required => true %>
    </div>
    <div class="input-options">
      <%= f.label :title%>
      <%= f.text_field :title, :required => true %>
    </div>
    <div class="input-options">
      <%= f.label :hint %>
      <%= f.text_field :description, :required => true %>
    </div>
    <%= f.hidden_field :deck_id, :value => @deck.id %>
    <div class="form-button">
      <%= f.submit 'Save Card', class: 'button-user' %>
    </div>
  </fieldset>
  <% end %>

app/views/decks/new.html.erb
<div class="form-container">

<h2 class="sub-title"> CREATE A NEW DECK </h2>

<% if @errors %>
  <% @errors.each do |error| %>
    <p class="error"><%= error %></p>
  <% end %>
<% end %>

<%= form_for @deck do |f| %>
<fieldset id="form">
  <div class="input-options">
    <%= f.label :name %>
    <%= f.text_field :name, :minlength => 5, :required => true %>
  </div>
  <div class="form-button">
  <%= f.submit 'Save Deck', class: 'button-user' %>
  </div>
</fieldset>
<% end %>

</div>

app/views/decks/show.html.erb
<div class="deck-nav">
	<h2 class="deck-title"><%= @deck.name %></h2>
	<div class="card-add-button">
		<%= link_to 'ADD CARD', new_deck_card_path(@deck.id) %>
	</div>
</div>	

<div class="card-main">
	<% @deck.cards.each do |card| %>
		<section class="container">
			<div class="card-title"><%= card.name %></div>
			<div id="card">
				<figure class="front">
					<%= image_tag card.avatar.url(:medium), :class => "img_preview" %>
				</figure>
				<figure class="back">
					<%= card.description %>
				</figure>
			</div>
		</section>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ReMember</title>
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
	<meta charset="utf-8"> 
</head>
<body>

	<nav class="navigation-bar">
	<%= link_to(image_tag("Logo.png",:class=>"logo"), root_path) %>
		<ul class="nav-options">
			<% if current_user %>
				<li class="nav-link"><%= link_to current_user.username, user_path(current_user) %></li>
				<li class="nav-link"><%= link_to 'Log Out', session_path(current_user), method: :delete %> </li>
			<% else %>
				<li class="nav-link"><%= link_to 'Sign Up', new_user_path %></li>
				<li class="nav-link"><%= link_to 'Log In', new_session_path %></li>
			<% end %>
		</ul>
	</nav>

	<main>
	<%= yield %>
	</main>

</body>
</html>

app/views/rounds/show.html.erb
<div class="quiz-info">

	<h1 class="guess-title"> Quizing <%= @round.deck.name %> </h1>

		<% if @round.deck.cards.empty?  %>

			<h3 class="alert"> NO CARDS IN DECK </h3>

		<% elsif @round.complete? %>

			<h2 class="sub-title"> Round Statistics </h2>

			<div class="answers">

				<div class="answer-info">

					<h3 class="sub-title"> You guessed right </h3>

					<% @round.guesses.each do |guess|%>

						<% if guess.right?  %>
						<div class="stats">
							<%=image_tag guess.card.avatar.url(:thumb), :class => "img_thumb" %> <%=guess.card.name %>
						</div>
						<% end %>

					<% end %>

				</div>

				<div class="answer-info">

					<h3 class="sub-title"> You guessed wrong </h3>

					<% @round.guesses.each do |guess|%>
						
						<% if guess.wrong?  %>
						<div class="stats">
							<%=image_tag guess.card.avatar.url(:thumb), :class => "img_thumb" %> <%=guess.card.name %>
						</div>
						<% end %>

					<% end %>

				</div>
			</div>

			<div class="guess-options">
			<%= link_to 'RETRY', deck_rounds_path(@round.deck.id), method: :post,:class=>"guess-btn btn-green"%>
			</div>

		<% else %>

			<div class="card-guess-main">
			<section class="guess-container">
				<div id="card">
					<figure class="front">
						<%= image_tag @round.current_card.avatar.url(:medium), :class => "img_preview" %>
					</figure>
					<figure class="back">
						<%= @round.current_card.description %>
					</figure>
				</div>
			</section>
			</div>

			<h1 class="guess-question"> DO YOU KNOW ME? </h1>

			<div class="guess-options">
				<%= link_to 'YES', round_guesses_path(card_id: @round.current_card.id, round_id: @round, answer: "YES"), method: :post,:class=>"guess-btn btn-green"  %>
				<%= link_to 'NO', round_guesses_path(card_id: @round.current_card.id, round_id: @round, answer: "NO"), method: :post,:class=>"guess-btn btn-red"%>
			</div>

		<% end %>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<fieldset id="form">
  <div class="input-options">
    <%= f.label :username %>
    <%= f.text_field :username, :minlength => 8 %>
  </div>
  <div class="input-options">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="input-options">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form-button">
  <%= f.submit 'Create Account', class: 'button-user' %>
  </div>
</fieldset>
<% end %>

<% if @errors %>
  <% @errors.each do |error| %>
    <p class="error"><%= error %></p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1 class="profile-title"> Welcome, <%= current_user.username %> </h1>

<div class="profile-nav">
	<div class="deck-add-button"><%= link_to 'Create Deck',new_deck_path%> </div>
	<div class="heading"> My Decks </div>
	<div class="heading"> My Cards </div>	
</div>

<div class="decks-container">

	<% @user.decks.each do |deck| %>

		<div class ="deck-container">
			<h4><%= link_to deck.name, deck_path(deck.id)%> (<%=deck.cards.size%>)</h4>
			<h5><%= link_to 'Play Deck', deck_rounds_path(deck.id), :method => :post%> | <%= link_to 'Add Card', new_deck_card_path(deck.id) %> | <%= link_to "Delete Deck", delete_deck_path(id:deck.id), method: :delete, data: {confirm: 'Are you sure you want to delete this deck?'} %></h5>
		</div>

	<% end %>

</div>

<div class ="cards-container">

	<% @user.cards.each do |card| %>
	<div class="card-main-profile">
		<section class="container">
			<div class="card-title"><%= card.name %></div>
			<div id="card">
				<figure class="front">
					<%= image_tag card.avatar.url(:medium), :class => "img_preview" %>
				</figure>
				<figure class="back">
					<div class="card-stats">
						<%= card.description %>
						<p class="right-text">
						Right: <%= card.number_right %>
						</p>
						 <p class="wrong-text">
						Wrong:<%= card.number_wrong %>
						</p>
					</div>
				</figure>
			</div>
		</section>
	</div>
	<% end %>

</div>

app/views/welcome/index.html.erb
	<div class="welcome-page">
		<div class="first-div">
			<img src='assets/Handshake.jpg'>
		</div>

		<div class="second-div v-wrap">
			<div class="v-box">
				<p class=welcome-title> What is Re Member</p>
				<p class=welcome-information><b>Re Member</b> is a web application that seeks to help people that have strong facial recognition habilities but struggle <b>Re Member</b>-ing names.</p>
				<p class=welcome-information>Through our easy to use web-game users can create decks of cards containing certain information about people they want to remember and play through these decks to excercise name to face memory.</p>
				<p class=welcome-information>Never again will you forget a name and even if you do, you will have a card to help you!</p>
			</div>
		</div>

		<div class="third-div v-wrap">
			<div class="v-box">
				<p class="welcome-title blue"> Just Follow These Easy Steps</p>
				<div class="steps">
					<div class="icon">
						<img src='assets/Login.png'>
						<h5>SIGN UP OR LOGIN</h5>
					</div>
					<div class="icon">
						<img src="assets/Create.png">
						<h5>CREATE A DECK AND CARDS</h5>
					</div>
					<div class="icon">
						<img src="assets/Play.png">
						<h5>PLAY THROUGH A DECK</h5>
					</div>
					<div class="icon">
						<img src="assets/Memorize.png">
						<h5>MEMORIZE NAMES</h5>
					</div>
				</div>
			</div>
		</div>

		<div class="fourth-div">
			<p class=welcome-footer-information>Copyright © 2016 Created by Luis Fernando Plaz.</p>
		</div>
	</div>